version: "3.0"
services:
  server:
    container_name: z32_server1_2
    build: ./pyserver1_2
    networks:
      network1:
        aliases:
          - z32_server1_2
    tty: true
    cap_add:
    - NET_ADMIN
  client:
    container_name: z32_client1_2
    build: ./pyclient1_2
    networks:
      network1:
        aliases:
          - z32_client1_2
    tty: true
    cap_add:
    - NET_ADMIN
    depends_on:
      - server

networks:
  network1:
    name: z32_network
    external: true